import type { TeamMember } from "@/lib/types/team"

// Update the existing users array with salary and responsibilities
export const teamMembers: TeamMember[] = [
  {
    id: "user1",
    name: "James Mwangi",
    role: "Farm Manager",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "Online",
    email: "james.mwangi@bananatracker.com",
    phone: "+254712345678",
    salary: 10000,
    startDate: "2022-03-15",
    location: "Karii",
    responsibilities: [
      "Oversee daily farm operations",
      "Manage farm staff",
      "Implement cultivation strategies",
      "Monitor crop health and growth",
      "Report to farm owner",
    ],
    skills: ["Farm Management", "Leadership", "Crop Planning", "Staff Training"],
  },
  {
    id: "user2",
    name: "Grace Wanjiru",
    role: "Agronomist",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "Busy",
    email: "grace.wanjiru@bananatracker.com",
    phone: "+254723456789",
    salary: 28000,
    startDate: "2022-05-10",
    location: "Nairobi",
    responsibilities: [
      "Soil testing and analysis",
      "Pest and disease management",
      "Crop nutrition planning",
      "Yield optimization strategies",
      "Training farm workers on best practices",
    ],
    skills: ["Soil Science", "Pest Management", "Crop Nutrition", "Data Analysis"],
  },
  {
    id: "user3",
    name: "Lynnette Nyanjau",
    role: "Farm Conultant",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "Away",
    email: "shao@gmail.com",
    phone: "+254734567890",
    salary: 90000,
    startDate: "2022-06-20",
    location: "Karii",
    responsibilities: [
      "Schedule and oversee harvesting activities",
      "Quality control of harvested produce",
      "Coordinate with buyers and logistics",
      "Manage post-harvest handling",
      "Record keeping of harvest data",
    ],
    skills: ["Harvest Planning", "Quality Control", "Logistics", "Record Keeping"],
  },
  {
    id: "user4",
    name: "Mary Njeri",
    role: "Administrative Assistant",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "Offline",
    email: "mary.njeri@bananatracker.com",
    phone: "+254745678901",
    salary: 18000,
    startDate: "2022-08-05",
    location: "Nairobi",
    responsibilities: [
      "Office administration",
      "Record keeping and documentation",
      "Communication with stakeholders",
      "Scheduling meetings and appointments",
      "Supporting management team",
    ],
    skills: ["Administration", "Communication", "Organization", "MS Office"],
  },
  {
    id: "user5",
    name: "John Kamau",
    role: "Farm Worker",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "Online",
    email: "john.kamau@bananatracker.com",
    phone: "+254756789012",
    salary: 10000,
    startDate: "2022-09-15",
    location: "Karii",
    responsibilities: [
      "Planting and cultivation",
      "Irrigation management",
      "Weed control",
      "Harvesting assistance",
      "General farm maintenance",
    ],
    skills: ["Cultivation", "Irrigation", "Harvesting", "Farm Maintenance"],
  },
]
